title: Hi! we are the Debuggers
description: CSP 2025-2026

# ← use your real account/urls:
url: "https://guyyuefangyuan.github.io"   # no trailing slash
baseurl: "/Portfolio"                      # project pages = /<repo-name>

github_username: guyyuefangyuan
github_repo: "Portfolio"

remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-feed
